version: '3'
services:
    notebook:
        image: notebook
        user: root
        build:
            context: .
        ports:
            - 8888:8888
        environment:
            - HOST_DIR=${PWD}
            - GRANT_SUDO=yes
            - CHOWN_HOME=yes
        volumes:
            - .:/home/jovyan/work
            # set -gx DOCKER_SOCK (docker context show | xargs docker context inspect | jq -r '.[0].Endpoints.docker.Host' | sed 's|unix://||')
            # - $DOCKER_SOCK:/var/run/docker.sock:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw
